# Generated by Django 4.0.3 on 2022-03-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postkon_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_img',
            field=models.ImageField(null=True, upload_to='images_uploaded'),
        ),
    ]
