# Generated by Django 4.0.3 on 2022-03-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postkon_webapp', '0002_user_avatar_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
