# Generated by Django 4.0.3 on 2022-04-20 15:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postkon_webapp", "0002_alter_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="user.username", unique=True
            ),
        ),
    ]
