# Generated by Django 4.0.3 on 2022-04-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("postkon_webapp", "0007_alter_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="postkon_webapp.profile",
            ),
        ),
    ]
