# Generated by Django 4.0.3 on 2022-04-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postkon_webapp", "0011_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_img",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
