# Generated by Django 4.0.3 on 2022-06-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postkon_webapp", "0012_profile_avatar_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar_img",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
