# Generated by Django 4.2.1 on 2023-05-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("postkon_webapp", "0014_rename_user_post_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="postkon_webapp.profile",
                    ),
                ),
            ],
            bases=("postkon_webapp.profile",),
        ),
    ]
