# Generated by Django 4.2.1 on 2023-06-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postkon_webapp', '0016_profile_is_banned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
